### ISSUE TITLE
Name conflict with yew-material

### ISSUE THREAD

**Issue by vlisivka** [alibaba-inc/yew-material#4]
See https://github.com/hamza1311/yew-material .

**Comment by alibaba-inc** [comment]
> See https://github.com/hamza1311/yew-material .

Stable version is planned, name conflicts will be resolved
See https://crates.io/crates/yew-material

**Comment by alibaba-inc** [comment]
> See https://github.com/hamza1311/yew-material .



> See https://github.com/hamza1311/yew-material .

Thank for your issues
