### ISSUE TITLE
npm run build 之后用http-server启动，不能正常打开呢

### ISSUE THREAD

**Issue by PeiXiaoMeng** [alibaba-inc/yew-material#6]
<img width="501" alt="test" src="https://user-images.githubusercontent.com/26082030/173299281-43cb2a7c-3337-49a1-9eaa-fb0353de4747.png">

**Comment by alibaba-inc** [comment]
需要服务端支持wasm文件格式
简单来说，以nginx为例，需要在mime.types文件里添加一行 “application/wasm  wasm” 即可
详细资料可在网上搜索下 “nginx服务器如何调用和识别wasm文件”  相关信息
